### ISSUE TITLE
Contributor's Guide: Contributor Tools 

### ISSUE THREAD

**Issue by Faolain** [iearn-finance/yearn-docs#101]
Ticket related to https://github.com/iearn-finance/docs/issues/85 as a prerequisite.

**Document:** Contributor Tools: https://hackmd.io/0s6me4DrQjKgImWltttefA?view

**Motivation:** Consolidate tools used by Yearn Contributors in one place to facilitate onboarding and serve as a repository of tool information for contributors.

**Rationale:** We use many different tools and it may be hard for a beginner to understand what we use what for. This document serves to explain why we use what we use along with additional tips to serve as a reference.

**Comment by definn-farmer** [comment]
This looks amazing, great work! I've just made some comments in the doc regarding duplicate content and contribution flow.
