### ISSUE TITLE
Spanish Docs

### ISSUE THREAD

**Issue by Faolain** [iearn-finance/yearn-docs#146]
Documentation forked from official github.
https://github.com/juafrapat/docs/tree/spanish

@miguel Oct 31 at 2:24 PM
@ppwdp PR created with some fixes: juafrapat/docs: Pull Request 2 how-to-guides and FAQ reviewed

Miguel y Juanma Franco

**Comment by miguel567** [comment]
@juafrapat  I believe we can close this ticket: FAW and your how to's are live on the spanish site.
