### ISSUE TITLE
Spanish - FAQ v1

### ISSUE THREAD

**Issue by Faolain** [iearn-finance/yearn-docs#150]
https://hackmd.io/@yearn/HJ9O044mw

- Darkghosty copied from Spanish- All YIPs Summary https://github.com/iearn-finance/yearn-docs/issues/151

**Comment by DarkGhost7** [comment]
this has been translated on our spanish fork https://juafrapat.gitbook.io/espanol/v/spanish/faq

**Comment by miguel567** [comment]
confirmed by @juafrapat . Closing
