### ISSUE TITLE
Spanish - All YIPs

### ISSUE THREAD

**Issue by Faolain** [iearn-finance/yearn-docs#158]
https://github.com/juafrapat/YIPS/tree/patch-1/YIPS

Miguel Cabeza Oct 23 at 3:16 PM
@ppwdp I've reviewed readme.md and faq.md until it is translated. Minor typos. all good!

Juanma Franco Oct 8 at 2:59 AM
@miguelcabeza3 Done, thanks for reviewing it.

Miguel Cabeza joined this card
Oct 7 at 4:46 PM
Miguel Cabeza Oct 7 at 4:45 PM
@ppwdp just created a PR to your patch-1 branch: juafrapat/YIPS: Pull Request 1

Darkghosty moved this card from In progress to Translated

Sep 26 at 11:20 AM
Darkghosty Sep 26 at 11:20 AM
Awesome!

Reply
Juanma Franco Sep 26 at 11:13 AM
Done and checked!

Juanma Franco Sep 25 at 5:50 PM
Last YIP should be done this weekend. I would like to ask for feedback if someone can, although I have to give it a second look after I it finished.

Darkghosty Sep 16 at 10:46 AM
Almost half done

**Comment by miguel567** [comment]
If I remember correctly, I reviwed all YIPS already in Spanish.
@juafrapat did you translate all of them? We need to discuss where to publish this ones, as I'm not sure there is a place in DOCS, maybe we can link to the repo form DOCS? do you know how it is done in the English verison?

**Comment by juafrapat** [comment]
I think it’s publish in other website (the English version). The Spanish translation was just merged #181 and can be seen here as a new section in the documentation. https://docs.yearn.finance/v/spanish/yips.
