### ISSUE TITLE
Contributor's Guide: Writing Style Guide

### ISSUE THREAD

**Issue by Faolain** [iearn-finance/yearn-docs#98]
Ticket related to https://github.com/iearn-finance/docs/issues/85 as a prerequisite.

**Document:** Writing Style Guide: https://hackmd.io/dXQecpkJQX6XRy4y7k7j3g

**Motivation:** Standardize Yearn documentation language for consistency and to ease comprehensibility.  

**Rationale**: Inconsistent language can make it hard for newcomers to the Yearn ecosystem understand how Yearn products work and how to contribute to the community.

**Comment by Faolain** [comment]
Apologies for the tag @dudesahn (hopefully I got the right one haha). I know you've been working on Naming Conventions & Standards, the above doc has a space for that in order to standardize/formalize any future documentation. Whenever you get a chance feel free to add it into that section or add/edit/remove anything you feel seems right :)

**Comment by dudesahn** [comment]
Yes! I think I'm the only one who has this name anywhere haha. Once we get everything finalized (we're so close!) I can update these docs as well, thanks for pointing me in the right direction.

**Comment by dudesahn** [comment]
@Faolain how does this work? Do I just update the hackMD document and then you'll update the relevant .md file?

**Comment by dudesahn** [comment]
I'm pretty much doing a brain dump for that section right now. It may not all be relevant to this part of the docs, but I wanted to get it down on paper and then we could move it to the right place after.

**Comment by Faolain** [comment]
Perfect thanks so much @dudesahn! Yeah that works we can always edit if need be. And yep I'll submit a PR once a review is done.

**Comment by Faolain** [comment]
No worries at all I think that makes sense, we can always add a link to "Learn More <here>". Really appreciate it!

**Comment by definn-farmer** [comment]
I've just made a comment about replacing the Naming Convention content for the published link, to avoid duplicates. Otherwise looks great to me.

**Comment by Faolain** [comment]
PR submitted
